!CUDA_VISIBLE_DEVICES=0 python train_ditto.py \
  --task Dirty/Walmart-Amazon \
  --batch_size 32 \
  --max_len 256 \
  --lr 3e-5 \
  --n_epochs 20 \
  --finetuning \
  --lm t5 \
  --fp16 \
  --da drop_col \
  --save_model
